export const mockPersonLetterItem = [
  {
    id: 6,
    letterNo: '',
    letterDate: '',
    letterAgency: '',
    note: '',
    uploadFile: '',
    uploadDate: '',
    numThDegs: '',
    numNonThDegs: '',
    replyNo: '',
    replyDate: '',
    worker: '',
    status: '',
    lastUpdate: '',
    supervisor: '',
    warn: true,
  },
]
